# api/routes/chat.py
"""
Endpoints للمحادثة الذكية
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List

from agents.general.researcher_agent import ResearcherAgent
from agents.general.qa_agent import QAAgent
from knowledge_base.vector_store.embeddings import EmbeddingsGenerator
from knowledge_base.vector_store.memory_store import MemoryVectorStore
from knowledge_base.retrieval.hybrid_search import HybridSearchEngine
from utilities.logger import logger

router = APIRouter(prefix="/chat", tags=["Chat"])

# تهيئة المكونات
embeddings = EmbeddingsGenerator()
vector_store = MemoryVectorStore()
search_engine = HybridSearchEngine(embeddings, vector_store)

# إنشاء الوكلاء
researcher_agent = ResearcherAgent(search_engine)
qa_agent = QAAgent()


class ChatRequest(BaseModel):
    """نموذج طلب المحادثة"""
    query: str
    use_search: bool = True
    top_k: Optional[int] = 5
    index_name: Optional[str] = "general"
    agent: Optional[str] = "auto"  # auto, researcher, qa


class ChatResponse(BaseModel):
    """نموذج رد المحادثة"""
    success: bool
    query: str
    answer: str
    agent_used: str
    sources: Optional[List[dict]] = None
    total_sources: Optional[int] = 0


@router.post("/message", response_model=ChatResponse)
async def chat_message(request: ChatRequest):
    """
    إرسال رسالة ومحادثة ذكية
    
    Args:
        request: طلب المحادثة
        
    Returns:
        ChatResponse: الرد
    """
    logger.info(f"Chat request: {request.query[:50]}...")
    
    try:
        # اختيار الوكيل
        if request.agent == "auto":
            # إذا طلب بحث، استخدم الباحث
            if request.use_search:
                selected_agent = researcher_agent
            else:
                selected_agent = qa_agent
        elif request.agent == "researcher":
            selected_agent = researcher_agent
        elif request.agent == "qa":
            selected_agent = qa_agent
        else:
            raise HTTPException(
                status_code=400,
                detail=f"Unknown agent: {request.agent}"
            )
        
        # تنفيذ المهمة
        result = await selected_agent.execute({
            "query": request.query,
            "top_k": request.top_k,
            "index_name": request.index_name,
            "use_memory": True
        })
        
        if not result.get("success"):
            raise HTTPException(
                status_code=500,
                detail=result.get("error", "Agent execution failed")
            )
        
        # إعداد الرد
        response = ChatResponse(
            success=True,
            query=request.query,
            answer=result["answer"],
            agent_used=selected_agent.name,
            sources=result.get("sources"),
            total_sources=result.get("total_sources", 0)
        )
        
        logger.info(f"✅ Chat response generated by {selected_agent.name}")
        return response
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Chat error: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Chat processing failed: {str(e)}"
        )


@router.get("/agents")
async def list_agents():
    """قائمة الوكلاء المتاحين"""
    return {
        "agents": [
            {
                "name": researcher_agent.name,
                "description": researcher_agent.description,
                "stats": researcher_agent.get_stats()
            },
            {
                "name": qa_agent.name,
                "description": qa_agent.description,
                "stats": qa_agent.get_stats()
            }
        ]
    }


@router.post("/reset-memory")
async def reset_memory():
    """إعادة تعيين ذاكرة المحادثة"""
    researcher_agent.reset_memory()
    qa_agent.reset_memory()
    
    return {
        "success": True,
        "message": "Memory reset for all agents"
    }